 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: aircraft                                                    
     # Surfaces =   5
     # Strips   =  50
     # Vortices = 250

  Sref =  87.475       Cref =  3.7750       Bref =  53.929    
  Xref =  0.0000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.97619     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09393     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =  -2.62609
  CZtot =  -0.50167     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.50000
  CDtot =   0.10247
  CDvis =   0.10000     CDind = 0.0024670
  CLff  =   0.49978     CDff  = 0.0025779    | Trefftz
  CYff  =   0.00000         e =    0.9276    | Plane  


 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =  10.582474    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.621081
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.248894
 y  mom.  Cm |    Cma = -58.934010    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.310318

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq = 130.906952    CLr =  -0.000000
 y  force CY |    CYp =  -0.028705    CYq =   0.000000    CYr =   0.689812
 x' mom.  Cl'|    Clp =  -0.958626    Clq =   0.000001    Clr =   0.346782
 y  mom.  Cm |    Cmp =  -0.000001    Cmq =-791.009460    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.034154    Cnq =  -0.000000    Cnr =  -0.415796

 Neutral point  Xnp =  21.023052

 Clb Cnr / Clr Cnb  =   0.961681    (  > 1 if spirally stable )
