 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: aircraft                                                    
     # Surfaces =   5
     # Strips   =  50
     # Vortices = 250

  Sref =  61.220       Cref =  4.1950       Bref =  33.929    
  Xref =  0.0000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   1.03779     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09516     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =  -1.96569
  CZtot =  -0.50181     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   0.50000
  CDtot =   0.10423
  CDvis =   0.10000     CDind = 0.0042306
  CLff  =   0.49955     CDff  = 0.0042854    | Trefftz
  CYff  =  -0.00000         e =    0.9858    | Plane  


 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =  10.743652    CLb =   0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.858001
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.317604
 y  mom.  Cm |    Cma = -47.517529    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.709065

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq = 111.603767    CLr =  -0.000000
 y  force CY |    CYp =  -0.249851    CYq =  -0.000003    CYr =   1.573069
 x' mom.  Cl'|    Clp =  -0.895328    Clq =  -0.000001    Clr =   0.551033
 y  mom.  Cm |    Cmp =   0.000001    Cmq =-555.152588    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =   0.135176    Cnq =   0.000003    Cnr =  -1.496379

 Neutral point  Xnp =  18.553843

 Clb Cnr / Clr Cnb  =   1.216365    (  > 1 if spirally stable )
