"""
File name : aircraft noise function
Author    : Alejandro Rios
Email     : aarc.88@gmail.com
Date      : February 2021
Last edit : 
Language  : Python 3.8 or >
Aeronautical Institute of Technology - Airbus Brazil

Description:
    - This function evaluates the noise generated by the aircraft during takeoff phase
Inputs:
    -
Outputs:
    -
TODO's:
    -

"""
# =============================================================================
# IMPORTS
# =============================================================================
from framework.Noise.takeoff_noise import takeoff_noise
# =============================================================================
# CLASSES
# =============================================================================

# =============================================================================
# FUNCTIONS
# =============================================================================
def aircraft_noise():

    
    
    # takeoff noise
    takeoff_noise()

    return
# =============================================================================
# MAIN
# =============================================================================

# =============================================================================
# TEST
# =============================================================================
